FN log bold cyan "- Updating installed $PDF_LATEX_TEMPLATE_NAME template"

mkdir -p "$PDF_PANDOC_TEMPLATE_DIRECTORY"
if (( $# > 0 ))
then
  FN log light cyan "- $1 --> $PDF_PANDOC_TEMPLATE_DIRECTORY/$PDF_LATEX_TEMPLATE_NAME.latex"
  cp "$1" "$PDF_PANDOC_TEMPLATE_DIRECTORY/$PDF_LATEX_TEMPLATE_NAME.latex"
else
  FN log light cyan "- $PDF_LATEX_SIMPLE_TEMPLATE_FILE --> $PDF_PANDOC_TEMPLATE_DIRECTORY/$PDF_LATEX_TEMPLATE_NAME.latex"
  cp "$PDF_LATEX_SIMPLE_TEMPLATE_FILE" "$PDF_PANDOC_TEMPLATE_DIRECTORY/$PDF_LATEX_TEMPLATE_NAME.latex"
fi