local text="$1"
text="${text//&&/AND}"
text="${text//||/OR}"
text="${text/\[\[/Brackets}"
text="${text/\(\(/Parentheses}"
text="${text/\'/}"
text="${text//[^a-zA-Z0-9_]/_}"
text="${text//__/_}"
text="${text//__/_}"
text="${text//__/_}"
text="${text#_}"
text="${text%_}"
printf '%s' "$text"